// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PlantaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlantaId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "a1",
                            CreatedAt = new DateTime(2026, 4, 20, 9, 8, 3, 0, DateTimeKind.Utc),
                            Nombre = "Área 1",
                            PlantaId = 1
                        });
                });

            modelBuilder.Entity("api.Models.DatoSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.HasIndex("Timestamp");

                    b.ToTable("DatosSensores");
                });

            modelBuilder.Entity("api.Models.Planta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Plantas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "p1",
                            CreatedAt = new DateTime(2026, 4, 20, 9, 8, 3, 0, DateTimeKind.Utc),
                            Nombre = "Planta 1"
                        });
                });

            modelBuilder.Entity("api.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Registro")
                        .HasColumnType("integer");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TipoGraficoId")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoGraficoId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("AreaId", "SensorId")
                        .IsUnique();

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("api.Models.TipoGrafico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Widget")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoGraficos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Time Series",
                            Nombre = "línea",
                            Widget = "line"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Indicador",
                            Nombre = "gauge",
                            Widget = "gauge"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Barras",
                            Nombre = "bar",
                            Widget = "bar"
                        });
                });

            modelBuilder.Entity("api.Models.Unidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Unidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Grados Celsius",
                            Nombre = "Temperatura",
                            Simbolo = "°C"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Libras por pulgada cuadrada",
                            Nombre = "Presión",
                            Simbolo = "PSI"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Voltios",
                            Nombre = "Voltaje",
                            Simbolo = "V"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Amperios",
                            Nombre = "Corriente",
                            Simbolo = "A"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Porcentaje",
                            Nombre = "Porcentaje",
                            Simbolo = "%"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Revoluciones por minuto",
                            Nombre = "RPM",
                            Simbolo = "RPM"
                        });
                });

            modelBuilder.Entity("api.Models.Area", b =>
                {
                    b.HasOne("api.Models.Planta", "Planta")
                        .WithMany("Areas")
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planta");
                });

            modelBuilder.Entity("api.Models.DatoSensor", b =>
                {
                    b.HasOne("api.Models.Sensor", "Sensor")
                        .WithMany("Datos")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("api.Models.Sensor", b =>
                {
                    b.HasOne("api.Models.Area", "Area")
                        .WithMany("Sensores")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.TipoGrafico", "TipoGrafico")
                        .WithMany("Sensores")
                        .HasForeignKey("TipoGraficoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("api.Models.Unidad", "Unidad")
                        .WithMany("Sensores")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("TipoGrafico");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("api.Models.Area", b =>
                {
                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("api.Models.Planta", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("api.Models.Sensor", b =>
                {
                    b.Navigation("Datos");
                });

            modelBuilder.Entity("api.Models.TipoGrafico", b =>
                {
                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("api.Models.Unidad", b =>
                {
                    b.Navigation("Sensores");
                });
#pragma warning restore 612, 618
        }
    }
}
