import {
  LayoutDashboard, Users, UserCircle, LogOut,
  Plug, WifiOff, AlertTriangle, AlertCircle,
  Gauge, Thermometer, Zap, Activity,
  Settings, ChevronDown, ChevronRight,
  ChevronLeft, ChevronRight as ChevronRightIcon,
  PanelLeft, Menu,
  Expand, Shrink, RotateCw, X, Pencil,
  Mail, MessageCircle, Smartphone, Send,
  Lock, Bell, User,
} from 'lucide-react';

export const icons = {
  dashboard: LayoutDashboard,
  users: Users,
  profile: UserCircle,
  logout: LogOut,
  connected: Plug,
  disconnected: WifiOff,
  reconnecting: RotateCw,
  alert: AlertTriangle,
  critical: AlertCircle,
  gauge: Gauge,
  temperature: Thermometer,
  voltage: Zap,
  activity: Activity,
  settings: Settings,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  sidebar: PanelLeft,
  menu: Menu,
  expand: Expand,
  shrink: Shrink,
  close: X,
  edit: Pencil,
  mail: Mail,
  message: MessageCircle,
  smartphone: Smartphone,
  send: Send,
  lock: Lock,
  bell: Bell,
  user: User,
};

export const iconSize = {
  nav: 20,
  inline: 16,
  header: 24,
};
